apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: monitoring-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Monitoring'
spec:
  tls:
  - hosts:
    - prometheus.formerr.tech
    - grafana.formerr.tech
    secretName: monitoring-tls
  rules:
  - host: prometheus.formerr.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus
            port:
              number: 9090
  - host: grafana.formerr.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000

---
# Basic Auth Secret for Monitoring Access
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-auth
  namespace: monitoring
type: Opaque
data:
  # admin:admin123 (base64 encoded)
  # Generate with: htpasswd -nb admin admin123 | base64 -w 0
  auth: YWRtaW46JGFwcjEkRzRrNzJ5clokL0pILnY2VGxpMzR4Q0QxUXdHVnN1MAo=
