apiVersion: v2
name: formerr
description: A Helm chart for Formerr application with integrated monitoring
type: application
version: 0.2.0
appVersion: "1.0.0"
keywords:
  - formerr
  - fastapi
  - nextjs
  - monitoring
home: https://github.com/your-org/formerr
sources:
  - https://github.com/your-org/formerr

dependencies:
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    
  - name: kube-prometheus-stack
    version: 55.5.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
    alias: prometheus
