apiVersion: apps/v1
kind: Deployment
metadata:
  name: formerr-backend
  namespace: formerr
  labels:
    app: formerr-backend
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: formerr-backend
  template:
    metadata:
      labels:
        app: formerr-backend
    spec:
      imagePullSecrets:
      - name: formerr-registry-secret
      containers:
      - name: backend
        image: registry.digitalocean.com/formerr-production/formerr-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: formerr-db-secret
              key: DATABASE_URL
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: formerr-app-secret
              key: GITHUB_CLIENT_ID
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: formerr-app-secret
              key: GITHUB_CLIENT_SECRET
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: formerr-app-secret
              key: JWT_SECRET
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: formerr-app-secret
              key: SESSION_SECRET
        - name: FRONTEND_SUCCESS_URL
          value: "https://formerr.tech/auth/success"
        - name: FRONTEND_ERROR_URL
          value: "https://formerr.tech/auth/error"
        - name: OAUTH_CALLBACK_URL
          value: "https://api.formerr.tech/auth/github/callback"
        - name: ALLOWED_ORIGINS
          value: "https://formerr.tech,https://api.formerr.tech"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: formerr-backend-service
  namespace: formerr
  labels:
    app: formerr-backend
spec:
  selector:
    app: formerr-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
